move scripts to own folder

diff --git a/rom/01atlasbootstrap b/rom/01atlasbootstrap
--- a/rom/01atlasbootstrap
+++ b/rom/01atlasbootstrap
@@ -56,7 +56,7 @@ if [[ ! -f $initfile ]] ;then
   else
     download="/system/bin/curl -s -k -L --fail --show-error --user $authUser:$authPass -o"
   fi
-  until $download $initfile $url/42atlas || { logger "Download 42atlas failed, exit script" ; exit 1; } ;do
+  until $download $initfile $url/scripts/42atlas || { logger "Download 42atlas failed, exit script" ; exit 1; } ;do
     sleep 2
   done
   logger "First boot: downloaded 42atlas"
diff --git a/scripts/42atlas b/scripts/42atlas
--- a/scripts/42atlas
+++ b/scripts/42atlas
@@ -195,7 +195,7 @@ mount -o remount,rw /system/etc/init.d
 
 # add atlas.sh
   if [[ ! -f /system/bin/atlas.sh ]] ;then
-    until $download $url/atlas.sh || { logger "42atlas: download atlas.sh failed, exit script" ; exit 1; } ;do
+    until $download $url/scripts/atlas.sh || { logger "42atlas: download atlas.sh failed, exit script" ; exit 1; } ;do
       sleep 2
     done
   fi
