more log changes

diff --git a/scripts/42atlas b/scripts/42atlas
--- a/scripts/42atlas
+++ b/scripts/42atlas
@@ -1,5 +1,5 @@
 #!/system/bin/sh
-# version 1.1
+# version 1.2
 
 logfile="/sdcard/aconf.log"
 aconf_download="/data/local/aconf_download"
@@ -27,16 +27,20 @@ wait_for_internet(){
 until ping -c1 8.8.8.8 >/dev/null 2>/dev/null || ping -c1 1.1.1.1 >/dev/null 2>/dev/null; do
     sleep 10
 done
-logger "Internet connection available"
+echo "`date +%Y-%m-%d_%T` 42atlas: internet connection available" >> $logfile
 }
 
 # logger
 logger() {
 if [[ ! -z $discord_webhook ]] ;then
-  echo "`date +%Y-%m-%d_%T` $1" >> $logfile
-  curl -S -k -L --fail --show-error -F "payload_json={\"username\": \"42atlas\", \"content\": \" $1 \"}"  $discord_webhook &>/dev/null
+  echo "`date +%Y-%m-%d_%T` 42atlas: $1" >> $logfile
+  if [[ ! -z $origin ]] ;then
+    curl -S -k -L --fail --show-error -F "payload_json={\"username\": \"42atlas\", \"content\": \" $1 \"}"  $discord_webhook &>/dev/null
+  else
+    curl -S -k -L --fail --show-error -F "payload_json={\"username\": \"42atlas\", \"content\": \" $origin\: $1 \"}"  $discord_webhook &>/dev/null
+  fi
 else
-  echo "`date +%Y-%m-%d_%T` $1" >> $logfile
+  echo "`date +%Y-%m-%d_%T` 42atlas: $1" >> $logfile
 fi
 }
 
@@ -64,13 +68,13 @@ if [[ "$current_mac" == "00:15:18:01:81:31" ]] ;then
   ifconfig eth0 up
   sleep 3
   set_mac $new_mac
-  logger "42atlas: changed mac from $current_mac to $new_mac"
+  logger "changed mac from $current_mac to $new_mac"
   wait_for_internet
 fi
 }
 
 repack_magisk(){
-logger "42atlas: starting magisk repackaging"
+logger "starting magisk repackaging"
 monkey -p com.topjohnwu.magisk 1
 sleep 30
 input tap 39 42
@@ -88,19 +92,19 @@ sleep 2
 }
 
 install_magisk() {
-until $download /sdcard/magisk.zip $url_magisk || { logger "42atlas: download magisk failed, exit script" ; exit 1; } ;do
+until $download /sdcard/magisk.zip $url_magisk || { logger "download magisk failed, exit script" ; exit 1; } ;do
    sleep 5
 done
 mkdir -p /cache/recovery
 touch /cache/recovery/command
 echo '--update_package=/sdcard/magisk.zip' >> /cache/recovery/command
-logger "42atlas: magisk set to be installed"
+logger "magisk set to be installed"
 cachereboot=1
 }
 
 check_magisk(){
 if [[ -f /sbin/magisk ]] ;then
-  logger "42atlas: setting magisk permissions"
+  logger "setting magisk permissions"
   [[ -f /sdcard/magisk.zip ]] && rm /sdcard/magisk.zip
   #check if shell has su root
   suid="$(id -u shell)"
@@ -108,20 +112,20 @@ if [[ -f /sbin/magisk ]] ;then
   if [[ "$suid" ]] && [[ "$pol" != 2 ]] ;then
     magisk --sqlite "DELETE from policies WHERE package_name='com.android.shell'"
     magisk --sqlite "INSERT INTO policies (uid,package_name,policy,until,logging,notification) VALUES($suid,'com.android.shell',2,0,1,1)"
-    logger "42atlas: shell granted su root access"
+    logger "shell granted su root access"
   fi
 fi
 # Install magisk.  If it already exists, check for an update
 if ! [[ -f /sbin/magisk ]] ;then
-  logger "42atlas: preparing magisk installation"
+  logger "preparing magisk installation"
   touch /sdcard/magisk_repackage
   install_magisk
 elif ! magisk -c|grep -q "$magisk_ver"; then
-  logger "42atlas: magisk update required"
+  logger "magisk update required"
   touch /sdcard/magisk_update
   install_magisk
 elif [[ -f /sdcard/magisk_repackage ]] ;then
-  logger "42atlas: magisk repackaging required"
+  logger "magisk repackaging required"
   # After installation the manager may not be fully installed.  Wait for it to show then repackage
   until [[ $(pm list packages com.topjohnwu.magisk) ]] ;do
     sleep 10
@@ -131,28 +135,28 @@ elif [[ -f /sdcard/magisk_repackage ]] ;then
     sleep 10
     # if repackaging didnt take place in 200 seconds, try again
     if ! (( $((r%20)) )); then
-      logger "42atlas: attempting to repackage magisk"
+      logger "attempting to repackage magisk"
       repack_magisk
     fi
     r=$((r+1))
   done
-  logger "42atlas: magisk successfully repackaged"
+  logger "magisk successfully repackaged"
   rm -f /sdcard/magisk_repackage
   sleep 10
 elif [[ -f /sdcard/magisk_update ]] ;then
   while [[ $(pm list packages com.topjohnwu.magisk) ]] ;do
     pm uninstall com.topjohnwu.magisk
-    logger "42atlas: magisk uninstalled"
+    logger "magisk uninstalled"
     sleep 3
   done
   rm -f /sdcard/magisk_update
 elif [[ $(pm list packages com.topjohnwu.magisk) ]] ;then
-  logger "42atlas: magisk installed and not repackaged, this should not happen"
+  logger "magisk installed and not repackaged, this should not happen"
 fi
 }
 
 install_gapps(){
-until /system/bin/curl -s -k -L --fail --show-error -o /sdcard/gapps.zip "$url_gapps" || { logger "42atlas: download gapps failed, exit script" ; exit 1; } ;do
+until /system/bin/curl -s -k -L --fail --show-error -o /sdcard/gapps.zip "$url_gapps" || { logger "download gapps failed, exit script" ; exit 1; } ;do
    sleep 5
 done
 
@@ -168,7 +172,7 @@ wait_for_internet
 
 # verify download credential file and set download
 if [[ ! -f $aconf_download ]] ;then
-  echo "`date +%Y-%m-%d_%T` file /data/local/aconf_download not found, exit script" >> $logfile && exit 1
+  logger "/data/local/aconf_download not found, exit script" && exit 1
 else
   url=$(grep url $aconf_download | awk -F "=" '{ print $NF }')
   authUser=$(grep authUser $aconf_download | awk -F "=" '{ print $NF }')
@@ -195,24 +199,24 @@ mount -o remount,rw /system/etc/init.d
 
 # add atlas.sh
   if [[ ! -f /system/bin/atlas.sh ]] ;then
-    until $download /system/bin/atlas.sh $url/scripts/atlas.sh || { logger "42atlas: download atlas.sh failed, exit script" ; exit 1; } ;do
+    until $download /system/bin/atlas.sh $url/scripts/atlas.sh || { logger "download atlas.sh failed, exit script" ; exit 1; } ;do
       sleep 2
     done
   fi
   chmod +x /system/bin/atlas.sh
-  logger "42atlas: downloaded atlas.sh"
+  logger "downloaded atlas.sh"
 
 # download versions file
-  until $download $aconf_versions $url/versions || { logger "42atlas: download versions file failed, exit script"; exit 1; } ;do
+  until $download $aconf_versions $url/versions || { logger "download versions file failed, exit script"; exit 1; } ;do
     sleep 2
   done
   dos2unix $aconf_versions
-  logger "42atlas: downloaded versions file"
+  logger "downloaded versions file"
 
 # add gapps to be installed
   if [[ ! $(pm list packages android.vending) ]] ;then
     install_gapps
-    logger "42atlas: downloaded gapps and set to be installed"
+    logger "downloaded gapps and set to be installed"
   fi
 
 #default stuff from mad rom, needed? doubt it will hurt
@@ -222,14 +226,14 @@ mount -o remount,rw /system/etc/init.d
   ! settings get secure location_providers_allowed|grep -q gps && settings put secure location_providers_allowed +gps
 # time to reboot as magisk isn't installed
   if (( "$cachereboot" )) ;then
-    logger "42atlas: rebooting into recovery mode for required installations"
+    logger "rebooting into recovery mode for required installations"
     echo '--wipe_cache' >> /cache/recovery/command
     reboot recovery
   fi
 
 # Install Atlas
   if [[ ! -d /data/data/com.pokemod.atlas/ ]] ;then
-    logger "42atlas: starting install of atlas"
+    logger "starting install of atlas"
     /system/bin/atlas.sh -ia
   fi
 
@@ -240,7 +244,7 @@ mount -o remount,rw /system/etc/init.d
     rm -f /sdcard/new_install
     rm -f /system/etc/init.d/01atlasbootstrap
     rm -f /sdcard/gapps.zip
-    logger "42atlas: config done, now acting as 55atlas"
+    logger "config done, now acting as 55atlas"
   fi
 mount -o remount,ro /system
 mount -o remount,ro /system/etc/init.d
